# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "vulnerability-scan" ]
  pull_request:
    branches: [ "vulnerability-scan" ]

jobs:
  owasp-dependency-check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run owasp
    - name: Archive vulnerability artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: |
          dependency-check-reports
  vulnerability-analysis-report:
    runs-on: ubuntu-latest
    needs: owasp-dependency-check
    steps:
    - uses: actions/checkout@v3
    - name: Download vulnerability artifacts
      uses: actions/download-artifact@v3
      with:
        name: dependency-check-report
    - run: ls -la
    - run: pip3 install openai
    - name: Fix vulnerabilities
      env:
        OPENAI_API_KEY: ${{ secrets.OPEN_AI_KEY }}
      run: |
        python3 fetchVulnerabilityNameAndDescription.py
    - name: Archive vulnerability artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vulnerability-analysis-report
        path: |
          ./report/index.html